#!/usr/bin/env python3
"""
render-vpn-config.py — Render Mihomo VPN sidecar configuration from validated JSON.

Enforces spec §12.5 & §12.6:
- Rejects dynamic proxy-providers (fail-closed for kill-switch firewall integrity).
- Requires static inline proxies under 'proxies:'.
- Configures TUN interface (device: tun0, stack: gVisor).
- Generates canonical configuration without anchors, aliases, tags, or escape sequences.

Usage:
  python3 render-vpn-config.py [INPUT_JSON] [OUTPUT_YAML]
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any


def _has_proxy_providers(obj: Any) -> bool:
    """Recursively check for proxy-providers key in any casing or variation."""
    if isinstance(obj, dict):
        for k, v in obj.items():
            if isinstance(k, str) and k.lower().replace("_", "-") == "proxy-providers":
                return True
            if _has_proxy_providers(v):
                return True
    elif isinstance(obj, list):
        for item in obj:
            if _has_proxy_providers(item):
                return True
    return False


def render_vpn_config(input_path: Path, output_path: Path) -> None:
    try:
        data = json.loads(input_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as err:
        raise SystemExit(f"Error: failed to read JSON configuration from {input_path}: {err}")

    # Extract mihomo configuration if embedded in samovar-config.json
    if "mihomo" in data and isinstance(data["mihomo"], dict):
        cfg = data["mihomo"].get("config", {})
    elif "config" in data and isinstance(data["config"], dict):
        cfg = data["config"]
    else:
        cfg = data

    # Strict semantic check: forbid proxy-providers anywhere in configuration
    if _has_proxy_providers(cfg):
        raise SystemExit(
            "Error: proxy-providers are not supported in VPN sidecar TUN mode. "
            "Define all endpoints under 'proxies:'."
        )

    proxies = cfg.get("proxies")
    if not proxies or not isinstance(proxies, list):
        raise SystemExit("Error: VPN sidecar configuration requires a non-empty 'proxies' list.")

    for i, proxy in enumerate(proxies):
        if not isinstance(proxy, dict) or not proxy.get("server") or not proxy.get("name") or not proxy.get("type"):
            raise SystemExit(f"Error: proxy entry #{i} must be a dictionary with 'name', 'type', and 'server'.")

    # Build canonical configuration
    tun_cfg = {
        "enable": True,
        "stack": "gVisor",
        "device": "tun0",
        "auto-route": True,
        "auto-detect-interface": True,
        "dns-hijack": ["127.0.0.11:53", "0.0.0.0:53"],
    }

    clean_config = {
        "mode": cfg.get("mode", "rule"),
        "mixed-port": cfg.get("mixed-port", 7890),
        "allow-lan": False,
        "log-level": cfg.get("log-level", "info"),
        "external-controller": cfg.get("external-controller", "127.0.0.1:9090"),
        "tun": cfg.get("tun", tun_cfg),
        "proxies": proxies,
        "proxy-groups": cfg.get("proxy-groups", []),
        "rules": cfg.get("rules", ["MATCH,DIRECT"]),
    }
    if "secret" in cfg:
        clean_config["secret"] = cfg["secret"]

    # ensure_ascii=False emits UTF-8 without unicode escape sequences (\uXXXX)
    yaml_text = json.dumps(clean_config, indent=2, ensure_ascii=False)
    header = (
        "# Generated by Samovar render-vpn-config.py from validated JSON.\n"
        "# Static inline proxies enforced for fail-closed firewall isolation.\n"
    )
    output_path.write_text(header + yaml_text + "\n", encoding="utf-8")
    print(f"Generated verified VPN configuration: {output_path}")


def main() -> None:
    input_file = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("samovar-config.json")
    if not input_file.is_file() and Path("mihomo-vpn.json").is_file():
        input_file = Path("mihomo-vpn.json")
    output_file = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("mihomo-vpn.yaml")
    render_vpn_config(input_file, output_file)


if __name__ == "__main__":
    main()
